[[apps]]
id = "w1"
title = "Workspace W1"
host = "w1.yourdomain.com"
upstream = "http://w1-app:80"
icon = "las la-th-large"
target_blank = true
enabled = true

[[apps]]
id = "w2"
title = "Workspace W2"
host = "w2.yourdomain.com"
upstream = "http://w2-app:80"
icon = "las la-th-large"
target_blank = true
enabled = true